  name: java CI deploy

  on:
    push:
      branches:
        - "deploy"
  permissions:
    contents: read

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '17'

        - name: make application-db.properties
          run: |
            touch ./src/main/resources/application-prod.yaml
            echo "${{ secrets.PROPERTIES_DEPLOY }}" > ./src/main/resources/application-prod.yaml

        - name: test
          run: |
            chmod +x ./gradlew
            ./gradlew test

        - name: build
          run: |
            ./gradlew clean build -x test
            
        - name: docker build
          run: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker build -t ${{ secrets.DOCKER_USERNAME }}/lottofinder:lastest .
            docker push ${{ secrets.DOCKER_USERNAME }}/lottofinder:lastest